function [F,M] = CalcTailForce(p,state)

  % Translate to old convention
  % -----------------------------------------------------
  R = [state.tailrx; state.tailry; zeros(1,length(state.tailrx))];
  U = [state.tailux; state.tailuy; zeros(1,length(state.tailux))];
  A = [state.tailax; state.tailay; zeros(1,length(state.tailax))];
  
  finHeight = p.finParams.height;
  finDepth = p.finParams.depth;
  
  CM = state.CM;
  UInf = InertialToBody(state.u,state.xi,state.theta,state.phi);
  W = InertialToBody(state.w,state.xi,state.theta,state.phi);
  
  density = p.fluidDensity;
  kViscosity = p.fluidkVisc;
  
    
  % Calculate forces
  % -----------------------------------------------------
  [F,M] = tailForces(R,U,A,finHeight,finDepth,CM,UInf,W,density,kViscosity);
  
function [F,M] = tailForces(R,U,A,finHeight,finDepth,CM,UInf,W,density,kViscosity)
% Description: 
%   Calculates force and moment generated by all of the tail elements
%   using Jordan's model (1992)
%
% Parameters : 
%  1) position of each plate in morpho space (3xnumSegments)
%  2) velocity of each plate in morpho space (3xnumSegments)
%  3) acceleration of each plate in morpho space (3xnumSegments)
%  4) max z of the plate in body space (1xnumSegments)
%  5) min z of the plate in morpho space (1xnumSegments)
%  6) center of mass vector in morpho space (3x1)
%  7) free stream velocity vector in morpho space (3x1)
%  8) rotation vector in morpho space (3x1)
%  9) density of medium (1x1)
%  10) kinematic viscosity of medium (1x1)
%  11) local time-independent normal reynold's number (1xnumSegments)
%  12) local time-independent tangential reynold's number (1xnumSegments)


  % Make center of mass into matrix
  % -----------------------------------------------------
  CM_t(1,:) = CM(1)*ones(1,size(R,2));
  CM_t(2,:) = CM(2)*ones(1,size(R,2));
  CM_t(3,:) = CM(3)*ones(1,size(R,2));
  CM = CM_t;
  
  clear CM_t
  
  % Go to center of mass coordinates
  % -----------------------------------------------------
  R = R-CM;

  % Calculate the tangent and normal vector of each plate
  % -----------------------------------------------------
  ds = sqrt(dot(diff(R,1,2),diff(R,1,2)));
  ds = [ds(1) ds];
 
  % the tangent vector 
  T = diff([zeros(3,1) R],1,2);
  T = [T(1,:)./ds; T(2,:)./ds];
  T_mag(1,:) = sqrt(dot(T,T));
  T_mag(2,:) = T_mag(1,:);
  T = T./T_mag;
  T(3,:) = 0;

  % the first normal vector
  N = [-T(2,:); T(1,:)]; 
  N_mag(1,:) = sqrt(dot(N,N));
  N_mag(2,:) = N_mag(1,:);
  N = N./N_mag;
  N(3,:) = 0;

  % the second normal vector 
  L = zeros(3,size(T,2));
  L(3,:) = ones(1,size(T,2)); 

  % Find relative velocity of each plate
  % -----------------------------------------------------
  W = meshgrid(W,1:size(U,2))';

  USeg(1,:) = U(1,:);
  USeg(2,:) = U(2,:);
  USeg(3,:) = zeros(1,size(U,2));
 
  UInf  = meshgrid(UInf',1:size(U,2))';
  USeg  = USeg + UInf + cross(W,R,1);

  ASeg(1,:) = A(1,:);
  ASeg(2,:) = A(2,:);
  ASeg(3,:) = zeros(1,size(A,2));

  cT  = dot(USeg,T,1);
  U_t = [cT.*T(1,:); cT.*T(2,:); cT.*T(3,:)]; % |T| = 1 by def
  
  cN  = dot(USeg,N,1);
  U_n = [cN.*N(1,:); cN.*N(2,:); cN.*N(3,:)] ; % |N| = 1 by def
  
  cL  = dot(USeg,L,1);
  U_l = [cL.*L(1,:); cL.*L(2,:); cL.*L(3,:)] ; % |L| = 1 by def
   
  cA  = dot(ASeg,N,1);
  A_n = [cA.*N(1,:); cA.*N(2,:); cA.*N(3,:)];
  clear cT cL cN cA;

  U_t_Mag = dot(U_t,U_t).^.5;
  U_n_Mag = dot(U_n,U_n).^.5;
  U_l_Mag = dot(U_l,U_l).^.5;

  % Find fin dimensions
  % -----------------------------------------------------
  segArea(1,:) = (finHeight + finDepth).*ds;
  segArea(2,:) = segArea(1,:);
  segArea(3,:) = segArea(1,:);

  % Calculate Reynold's numbers
  % -----------------------------------------------------   
  U_re = sqrt(dot(U,U));
  ReT = ds.*U_re/kViscosity;
  ReN = (finHeight+finDepth).*U_re/kViscosity;
  clear U_re
  
  % Skin friction (along tail)
  % -----------------------------------------------------
  Cd_t(1,:) = 0.664.*(ReT.^(-0.5));
  Cd_t(2,:) = Cd_t(1,:);
  Cd_t(3,:) = Cd_t(1,:);
  
  F_t = -(0.5).*Cd_t.*density.*segArea.*abs(U_t).*U_t;

  % Skin friction (perpendicular to tail)
  % -----------------------------------------------------
  Cd_l(1,:) = 0.664.*(ReT.^(-0.5));
  Cd_l(2,:) = Cd_l(1,:);
  Cd_l(3,:) = Cd_l(1,:);
  
  F_l   = -(0.5).*Cd_l.*density.*segArea.*abs(U_l).*U_l;
  
  % Normal force
  % -----------------------------------------------------
  Cd_n(1,:) = 3.42 + 20.37./ReN;
  Cd_n(2,:) = Cd_n(1,:);
  Cd_n(3,:) = Cd_n(1,:);
  
  F_n = -(0.5).*Cd_n.*density.*segArea.*abs(U_n).*U_n; 
  
  % Total force
  % -----------------------------------------------------
  F = F_t + F_l + F_n;

  % Moment calculation
  % -----------------------------------------------------
  M  = cross(R,F,1);

  % Sum over tail
  % -----------------------------------------------------
  F  = sum(F,2);
  M  = sum(M,2);


